{% set name = "supervision" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/supervision-{{ version }}.tar.gz
  sha256: 0bf49c2cd2e89439893899a02b846c5216c6a8e51392ac25c43c42843f5e2c1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.20.0
    - opencv
    - matplotlib-base
    - pyyaml

test:
  imports:
    - supervision
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/roboflow/supervision
  summary: A set of easy-to-use utils that will come in handy in any Computer Vision project
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - giswqs
