{% set name = "supervision" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/supervision-{{ version }}.tar.gz
  sha256: 6f83229f7f7866df7141370231f24dd3ac824c989f17854ed31f91dc0769fd5a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python
    - pip
    - poetry
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - numpy >=1.21.2
    - opencv
    - matplotlib-base
    - pyyaml
    - scipy
    - defusedxml
    - requests
    - tqdm


test:
  imports:
    - supervision
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/supervision/
  summary: Supervision is reusable computer vision tools.
  license: MIT
  license_file: LICENSE.md
  description: |
    [Supervision](https://supervision.roboflow.com) is reusable computer vision tools. 
    Whether you need to load your dataset from your hard drive, 
    draw detections on an image or video, or count how many detections are in a zone. 
  doc_url: https://supervision.roboflow.com
  dev_url: https://github.com/roboflow/supervision

extra:
  recipe-maintainers:
    - giswqs
    - onuralpszr
    - skalskiP
