{% set name = "supervision" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/supervision-{{ version }}.tar.gz
  sha256: bcce7d8dbd0e64116c5f493535a5eee902bbdf4f3cd16c6b05a3cd640a7fc40e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.20.0
    - opencv
    - matplotlib-base
    - pyyaml

test:
  imports:
    - supervision
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/roboflow/supervision
  summary: A set of easy-to-use utils that will come in handy in any Computer Vision project
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - giswqs
