{% set name = "supervision" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/supervision-{{ version }}.tar.gz
  sha256: 635039616604f60d232dd00db9e3d149cf4df3d7817e59dddeb058ec51c04351
  patches:
    - 0001-fix-opencv-package-convert.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python
    - pip
    - poetry
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - numpy >=1.21.2
    - opencv
    - py-opencv
    - matplotlib-base
    - pyyaml
    - scipy
    - defusedxml
    - requests
    - tqdm
    - gstreamer
    - gst-plugins-base
    - gst-plugins-good
    - pandas
    - pandas-stubs


test:
  imports:
    - supervision
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/supervision/
  summary: Supervision is reusable computer vision tools.
  license: MIT
  license_file: LICENSE.md
  description: |
    [Supervision](https://supervision.roboflow.com) is reusable computer vision tools. 
    Whether you need to load your dataset from your hard drive, 
    draw detections on an image or video, or count how many detections are in a zone. 
  doc_url: https://supervision.roboflow.com
  dev_url: https://github.com/roboflow/supervision

extra:
  recipe-maintainers:
    - giswqs
    - onuralpszr
    - skalskiP
    - LinasKo
